/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import javax.swing.JOptionPane;
import server.Server;

/**
 *
 * @author Filip
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    Server server;

    public FrmMain() {
        initComponents();
        btnPokreni.setEnabled(true);
        btnZaustavi.setEnabled(false);
        setLocationRelativeTo(null);
        setTitle("Server");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        btnKonfiguracija = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("DOBRO DOŠLI ");

        btnPokreni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPokreni.setForeground(new java.awt.Color(255, 255, 255));
        btnPokreni.setText("POKRENI SERVER");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnZaustavi.setForeground(new java.awt.Color(255, 255, 255));
        btnZaustavi.setText("ZAUSTAVI SERVER");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        btnKonfiguracija.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKonfiguracija.setForeground(new java.awt.Color(255, 255, 255));
        btnKonfiguracija.setText("KONFIGURACIJA");
        btnKonfiguracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfiguracijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnPokreni)
                        .addGap(65, 65, 65)
                        .addComponent(btnZaustavi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnKonfiguracija, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnKonfiguracija)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        try {
            if (server == null || !server.isAlive()) {
                server = new Server();
                server.start();
                JOptionPane.showMessageDialog(this, "Server je pokrenut");
                btnPokreni.setEnabled(false);
                btnZaustavi.setEnabled(true);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        try {
            server.stopServer();
            JOptionPane.showMessageDialog(this, "Server je zaustavljen");
            btnPokreni.setEnabled(true);
            btnZaustavi.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void btnKonfiguracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfiguracijaActionPerformed
        new FrmKonfiguracija(this, true).setVisible(true);
    }//GEN-LAST:event_btnKonfiguracijaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfiguracija;
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
