/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.form;

import domain.Korisnik;
import domain.Trening;
import domain.Vezba;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import table.model.TableModelVezba;
import ui.controller.Controller;

/**
 *
 * @author Filip
 */
public class FrmKreirajTrening extends javax.swing.JDialog {

    private Korisnik korisnik;
    private List<Vezba> vezbe = new ArrayList<>();
    /**
     * Creates new form FrmKreirajTrening
     */
    public FrmKreirajTrening(java.awt.Frame parent, boolean modal, Korisnik korisnik) {
        super(parent, modal);
        initComponents();
        this.korisnik = korisnik;
        setLocationRelativeTo(null);
        setTitle("Kreiranje novog treninga");
        napuniTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtTrajanje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBeleska = new javax.swing.JTextArea();
        btnSacuvajTrening = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVezbe = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnDodajVezbu = new javax.swing.JButton();
        btnObrisiVezbu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Trajanje (min):");

        jLabel3.setText("Beleška:");

        txtBeleska.setColumns(20);
        txtBeleska.setRows(5);
        jScrollPane1.setViewportView(txtBeleska);

        btnSacuvajTrening.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSacuvajTrening.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajTrening.setText("Sačuvaj trening");
        btnSacuvajTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajTreningActionPerformed(evt);
            }
        });

        tblVezbe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblVezbe);

        jLabel4.setText("Vežbe:");

        btnDodajVezbu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDodajVezbu.setText("Dodaj vežbu");
        btnDodajVezbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajVezbuActionPerformed(evt);
            }
        });

        btnObrisiVezbu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnObrisiVezbu.setText("Obriši vežbu");
        btnObrisiVezbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiVezbuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtTrajanje)
                            .addComponent(txtNaziv)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajVezbu)
                    .addComponent(btnObrisiVezbu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSacuvajTrening)
                .addGap(267, 267, 267))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodajVezbu)
                        .addGap(16, 16, 16)
                        .addComponent(btnObrisiVezbu)))
                .addGap(39, 39, 39)
                .addComponent(btnSacuvajTrening)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajTreningActionPerformed
        String naziv = txtNaziv.getText();
        String trajanje = txtTrajanje.getText();
        String beleska = txtBeleska.getText();
        
        if (validate(naziv, trajanje, beleska)) {
            try {
                Trening trening = new Trening();
                trening.setNaziv(naziv);
                trening.setTrajanje(Integer.parseInt(trajanje));
                trening.setBeleska(beleska);
                
                trening.setIDKorisnika(korisnik);
                
                TableModelVezba model = (TableModelVezba) tblVezbe.getModel();
                vezbe = model.getLista();
                trening.setVezbe(vezbe);
                
                Controller.getInstance().kreirajTrening(trening);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio trening", "Kreiran trening", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti novi trening", "Kreiran trening", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSacuvajTreningActionPerformed

    private void btnDodajVezbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajVezbuActionPerformed
        new FrmKreirajVezbu((Frame) this.getParent(), true, tblVezbe).setVisible(true);
    }//GEN-LAST:event_btnDodajVezbuActionPerformed

    private void btnObrisiVezbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiVezbuActionPerformed
        int red = tblVezbe.getSelectedRow();
        if (red != -1) {
            TableModelVezba model = (TableModelVezba) tblVezbe.getModel();
            Vezba v = model.getVezba(red);
            model.obrisiVezbu(red);
        }
        else {
            JOptionPane.showMessageDialog(this, "Morate selektovati red u tabeli", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiVezbuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajVezbu;
    private javax.swing.JButton btnObrisiVezbu;
    private javax.swing.JButton btnSacuvajTrening;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVezbe;
    private javax.swing.JTextArea txtBeleska;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtTrajanje;
    // End of variables declaration//GEN-END:variables

    private boolean validate(String naziv, String trajanje, String beleska) {
        boolean signal = true;
        
        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje naziv ne sme biti prazno", "Greška", JOptionPane.ERROR_MESSAGE);
            signal = false;
        }
        
        if (trajanje.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje trajanje ne sme biti prazno", "Greška", JOptionPane.ERROR_MESSAGE);
            signal = false;
        }
        
        if (!naziv.isEmpty()) {
            if (naziv.length() > 30) {
                JOptionPane.showMessageDialog(this, "Polje naziv ne sme biti duže od 30 karaktera", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }
        
        if (!trajanje.isEmpty()) {
            if (trajanje.matches("[a-zA-Z]+")) {
                JOptionPane.showMessageDialog(this, "Polje trajanje mora biti broj", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }
        
        if (!beleska.isEmpty()) {
            if (beleska.length() > 150) {
                JOptionPane.showMessageDialog(this, "Polje beleška ne sme biti duže od 150 karaktera", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }
        
        return signal;
    }

    private void napuniTabelu() {
        TableModelVezba model = new TableModelVezba();
        model.setLista(vezbe);
        tblVezbe.setModel(model);
    }
}
