/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.form;

import domain.Sprava;
import java.awt.Frame;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import ui.controller.Controller;

/**
 *
 * @author Filip
 */
public class FrmKreirajSpravu extends javax.swing.JDialog {

    private JComboBox cmbSprava;
    
    /**
     * Creates new form FrmNovaSprava
     */
    public FrmKreirajSpravu(Frame parent, boolean modal, JComboBox cmbSprava) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.cmbSprava = cmbSprava;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtMaxTezina = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Maksmalna težina:");

        btnSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSacuvaj.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvaj.setText("Sačuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNaziv)
                    .addComponent(txtMaxTezina, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSacuvaj)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaxTezina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String naziv = txtNaziv.getText();
        String maxTezina = txtMaxTezina.getText();

        if (validate(naziv, maxTezina)) {
            try {
                Sprava sprava = new Sprava();
                sprava.setNaziv(naziv);
                sprava.setMaxTezina(Double.parseDouble(maxTezina));
                Controller.getInstance().kreirajSpravu(sprava);
                napuniCmb();
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio novu spravu", "Kreiranje sprave", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti novu spravu", "Kreiranje sprave", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMaxTezina;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    private boolean validate(String naziv, String maxTezina) {
        boolean signal = true;

        if (naziv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje naziv ne sme da bude prazno", "Greška", JOptionPane.ERROR_MESSAGE);
            signal = false;
        }
        if (maxTezina.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje maksimalna težina ne sme da bude prazno", "Greška", JOptionPane.ERROR_MESSAGE);
            signal = false;
        }

        if (!naziv.isEmpty()) {
            if (naziv.length() > 30) {
                JOptionPane.showMessageDialog(this, "Polje naziv ne sme biti duze od 30 karaktera", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }

        if (!maxTezina.isEmpty()) {
            if (maxTezina.matches("[a-zA-Z]+")) {
                JOptionPane.showMessageDialog(this, "Maksimalna težina mora biti broj", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }

        return signal;
    }
    
     private void napuniCmb() {
        cmbSprava.removeAllItems();
        try {
            List<Sprava> sprave = Controller.getInstance().vratiSprave();
            for (Sprava sprava : sprave) {
                cmbSprava.addItem(sprava);
            }
            cmbSprava.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(FrmIzmeniVezbu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
