/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Korisnik;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ui.controller.Controller;

/**
 *
 * @author Filip
 */
public class FrmLogin extends javax.swing.JFrame {

    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setTitle("Prijava na sistem");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMejl = new javax.swing.JLabel();
        txtMejl = new javax.swing.JTextField();
        lblLozinka = new javax.swing.JLabel();
        btnPrijava = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();
        txtLozinka = new javax.swing.JPasswordField();
        lblRegistrujSe = new javax.swing.JLabel();
        btnNoviKorisnik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMejl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMejl.setText("Mejl:");

        txtMejl.setText("filip@gmail.com");

        lblLozinka.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLozinka.setText("Lozinka:");

        btnPrijava.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrijava.setForeground(new java.awt.Color(255, 255, 255));
        btnPrijava.setText("Prijavi se");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        btnZatvori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnZatvori.setForeground(new java.awt.Color(255, 255, 255));
        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        txtLozinka.setText("filip");

        lblRegistrujSe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegistrujSe.setText("Registrujte se");

        btnNoviKorisnik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNoviKorisnik.setForeground(new java.awt.Color(255, 255, 255));
        btnNoviKorisnik.setText("Napravi nalog");
        btnNoviKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviKorisnikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMejl)
                            .addComponent(lblLozinka))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMejl)
                            .addComponent(txtLozinka)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRegistrujSe, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNoviKorisnik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(btnPrijava)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZatvori)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMejl)
                    .addComponent(txtMejl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLozinka)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistrujSe)
                    .addComponent(btnNoviKorisnik)
                    .addComponent(btnPrijava)
                    .addComponent(btnZatvori))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        String mejl = txtMejl.getText();
        String lozinka = String.valueOf(txtLozinka.getPassword());
        if (validirajFormu(mejl, lozinka)) {
            
            try {
                Korisnik r = new Korisnik();
                r.setMejl(txtMejl.getText().trim());
                r.setLozinka(String.valueOf(txtLozinka.getPassword()));
                r = Controller.getInstance().login(r);
                //JOptionPane.showMessageDialog(this, "Uspešno prijavljivanje", "Prijava", JOptionPane.INFORMATION_MESSAGE);
                new FrmMain(r).setVisible(true);
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Neuspešno prijavljivanje, nalog ne postoji", "Prijava", JOptionPane.ERROR_MESSAGE);
            }
                
            
        }
    }//GEN-LAST:event_btnPrijavaActionPerformed

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
//        this.getTopLevelAncestor().setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_btnZatvoriActionPerformed

    private void btnNoviKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviKorisnikActionPerformed
        new FrmKreirajKorisnika(this, true).setVisible(true);
    }//GEN-LAST:event_btnNoviKorisnikActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoviKorisnik;
    private javax.swing.JButton btnPrijava;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel lblLozinka;
    private javax.swing.JLabel lblMejl;
    private javax.swing.JLabel lblRegistrujSe;
    private javax.swing.JPasswordField txtLozinka;
    private javax.swing.JTextField txtMejl;
    // End of variables declaration//GEN-END:variables

    private boolean validirajFormu(String mejl, String lozinka) {
        boolean signal = true;

        if (mejl.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje mejl je prazno", "Greška", JOptionPane.ERROR_MESSAGE);
            signal = false;
        }
        if (lozinka.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje lozinka je prazno", "Greška", JOptionPane.ERROR_MESSAGE);
            signal = false;
        }

        if (!mejl.isEmpty()) {
            if (mejl.length() < 6) {
                JOptionPane.showMessageDialog(this, "Mejl mora da sadrzi najmanje 6 karaktera", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }
        
        if (!lozinka.isEmpty()) {
            if (lozinka.length() < 4) {
                JOptionPane.showMessageDialog(this, "Lozinka mora da sadrzi najmanje 4 karaktera", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }
        
        if (!mejl.isEmpty()) {
            if (mejl.length() > 40) {
                JOptionPane.showMessageDialog(this, "Mejl moze da sadrzi najvise 40 karkatera", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }
        
        if (!lozinka.isEmpty()) {
            if (lozinka.length() > 20) {
                JOptionPane.showMessageDialog(this, "Lozinka moze da sadrzi najvise 30 karkatera", "Greška", JOptionPane.ERROR_MESSAGE);
                signal = false;
            }
        }

        return signal;
    }

}
