/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Korisnik;
import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.controller.Controller;

/**
 *
 * @author Filip
 */
public class FrmMain extends javax.swing.JFrame {

    private Korisnik korisnik;

    public FrmMain(Korisnik korisnik) {
        this.korisnik = korisnik;
        initComponents();
        setTitle(korisnik.getIme()+ " " + korisnik.getPrezime());
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        lblPrijavljeni.setText(korisnik.getIme()+ " " + korisnik.getPrezime());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPrijavljeni = new javax.swing.JLabel();
        btnOdjavi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTrening = new javax.swing.JMenu();
        menuItemKreirajTrening = new javax.swing.JMenuItem();
        menuItemPretraziTrenige = new javax.swing.JMenuItem();
        menuTeretana = new javax.swing.JMenu();
        menuItemPrikaziTeretane = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOBRO DOŠLI");

        lblPrijavljeni.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblPrijavljeni.setForeground(new java.awt.Color(0, 0, 255));
        lblPrijavljeni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnOdjavi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOdjavi.setForeground(new java.awt.Color(255, 255, 255));
        btnOdjavi.setText("Odjavi se");
        btnOdjavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviActionPerformed(evt);
            }
        });

        menuTrening.setText("Trening");

        menuItemKreirajTrening.setText("Kreiraj trening");
        menuItemKreirajTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKreirajTreningActionPerformed(evt);
            }
        });
        menuTrening.add(menuItemKreirajTrening);

        menuItemPretraziTrenige.setText("Pretraži treninge");
        menuItemPretraziTrenige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretraziTrenigeActionPerformed(evt);
            }
        });
        menuTrening.add(menuItemPretraziTrenige);

        jMenuBar1.add(menuTrening);

        menuTeretana.setText("Teretana");

        menuItemPrikaziTeretane.setText("Prikaži teretane");
        menuItemPrikaziTeretane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrikaziTeretaneActionPerformed(evt);
            }
        });
        menuTeretana.add(menuItemPrikaziTeretane);

        jMenuBar1.add(menuTeretana);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblPrijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnOdjavi)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPrijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOdjavi)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdjaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviActionPerformed
        try {
            Controller.getInstance().logout();
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOdjaviActionPerformed

    private void menuItemKreirajTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKreirajTreningActionPerformed
        new FrmKreirajTrening(this, true, korisnik).setVisible(true);
    }//GEN-LAST:event_menuItemKreirajTreningActionPerformed

    private void menuItemPretraziTrenigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretraziTrenigeActionPerformed
        new FrmPretraziTreninge(this, true, korisnik).setVisible(true);
    }//GEN-LAST:event_menuItemPretraziTrenigeActionPerformed

    private void menuItemPrikaziTeretaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrikaziTeretaneActionPerformed
        new FrmPrikaziTeretane(this, true, korisnik).setVisible(true);
    }//GEN-LAST:event_menuItemPrikaziTeretaneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblPrijavljeni;
    private javax.swing.JMenuItem menuItemKreirajTrening;
    private javax.swing.JMenuItem menuItemPretraziTrenige;
    private javax.swing.JMenuItem menuItemPrikaziTeretane;
    private javax.swing.JMenu menuTeretana;
    private javax.swing.JMenu menuTrening;
    // End of variables declaration//GEN-END:variables
}
